### ISSUE TITLE
 Ideas for more hammers

### ISSUE THREAD

**Issue by RaptorDread** [nudelauflauch/goilerweapony#2]
I love this mod, could there be more hammers? of other materials, such as copper, emerald, amathist, ruby ​​etc? It would be great, because I play with mods that add armor from those materials and it would be nice to have a hammer for each one, thank you very much for this great mod :,)

**Comment by MonsenioreWermeGigante** [comment]
Hi there, thank you for your positive feedback
We are open to support other compat mods, but i need the exact mod name you want to have supported.

**Comment by RaptorDread** [comment]
Hello! What great news, I am very happy to know that, the name of the mod I use is "Easy Emerald Tools & More" Link:
https://www.curseforge.com/minecraft/mc-mods/easy-emerald-tools

Would there also be the possibility in the future of adding some type of special attack or enchantments to the hammers? Like some bash, lightning bolt like the trident, or push something like that?


Again one of my favorite mods that should never be missing, since there are too many hammer mods, but they are all tools that replace the pickaxe, but these are for attack and damage with the plus of serving as tools but they do not specialize in that, I I love the mod, thank you very much :,)

**Comment by MonsenioreWermeGigante** [comment]
I really apreciate your wise words and thanks for the link :D
Currently we are trying to add new unique weapons to Goilerweapony but giving hammers some enchantmens is definitely a good idea, i will disguss that with my coder-buddy @nudelauflauch
